SERIAL_PORT = "COM6"
BAUD_RATE = 115200
COOLDOWN_SECONDS = 10

LOCATION = "WAREHOUSE_NAME"

# Replace with your deployed Google Apps Script Web App URL
SCRIPT_URL = "YOUR_SCRIPT_URL_HERE"

UI_UPDATE_DELAY = 0.2